language: android
android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-wear-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
